### ISSUE TITLE
Sample images

### ISSUE THREAD

**Issue by pvmm** [aoineko-fr/MSXgl#2]
Maybe these sample images could be in a docs folder (or you can ignore this issue and just reference them from here since https://msxvillage.fr/ doesn't allow linking from outside, but github allows it). 😉

![image](https://user-images.githubusercontent.com/7815819/158631313-2f817b46-1c58-485d-8a79-acc6167d40c2.png)
![image](https://user-images.githubusercontent.com/7815819/158631374-1090e6fd-cb35-41ff-9590-2f3f3e032998.png)
![image](https://user-images.githubusercontent.com/7815819/158631402-883caf71-f866-42c2-90ab-6ca132c5c897.png)

**Comment by aoineko-fr** [comment]
Thank you. We have corrected the problem with the MSXVillage. :)
