### ISSUE TITLE
Dirty screen with s_text sample in DOS2 mode

### ISSUE THREAD

**Issue by bradstallion** [aoineko-fr/MSXgl#39]
![image](https://github.com/aoineko-fr/MSXgl/assets/37795833/a6dd1682-88c4-41f6-beac-63ca2086b991)

Step to reproduce:

* `cd projects/samples/`
* add `Target = "DOS2"` to s_text.js
* `./build.sh s_text`
* open the emulator using emul/dos2/ as diska (e.g. `openmsx -machine Philips_NMS_8250 -ext msxdos2 -diska emul/dos2/`)

Using up and down arrows, the other fonts seem to be ok.

**Comment by aoineko-fr** [comment]
This is "expected" because this sample use BIOS font.
In the default ROM format for this sample, the BIOS and its font is available on page 0, but not in MSX-DOS format.

That said, I'm going to change the sample so that it starts on one of the fonts included in the program.

**Comment by aoineko-fr** [comment]
I pushed a new version of the sample where first displayed font is one of the font embedded into the program.

**Comment by bradstallion** [comment]
Thanks a lot for the explanation.
