### ISSUE TITLE
New ZX0 FAST ROM routine to be included

### ISSUE THREAD

**Issue by rodsiqbr** [aoineko-fr/MSXgl#42]
There's a code for FAST ZX0 decompressor that runs in ROM. I think it's a good addition to MSXgl.
If you want to take a look this is the link: https://github.com/uniabis/z80depacker/blob/master/dzx0_fastrom.asm

**Comment by aoineko-fr** [comment]
Hi rodsiqbr,
MSXgl already include 4 versions of the ZX0 unpacker: https://github.com/aoineko-fr/MSXgl/blob/main/engine/src/compress/zx0.c
What would be great a unpacker that unpack directly on VRAM. :)
