### ISSUE TITLE
VDP_SetMode should not touch the frequency setting

### ISSUE THREAD

**Issue by qbi70** [aoineko-fr/MSXgl#8]
When I do VDP_SetMode(VDP_MODE_SCREEN5); the VDP frequency is set to 50Hz, even if it was set to 60Hz before.
This is undesirable behavior. The VDP frequency should not be touched.

**Reproduction scenario:**
Program snippet:

    #include "msxgl.h"
    #include "vdp.h"
    
    void main()
    {
        VDP_SetMode(VDP_MODE_SCREEN5);
        while (true) {
            // no need to do anything
        }
    }

Start with e.g. CBIOS MSX2+ (which runs at 60Hz normally)

After the screen has been set, you can see in the *openMSX / menu / advanced / toys and utilities / info panel* that the frequency has been changed to 50Hz.

**Comment by aoineko-fr** [comment]
To prevent 50 Hz to be set on MSX2 you can either:
* Set `VDP_USE_DEFAULT_SETTINGS` to 0 (you will have to handle manually the reset of VDP registers)
* Set `VDP_INIT_50HZ` to `VDP_INIT_DEFAULT` (keep previous frequency setting)
